export const remixIconData = [{
  icon: "ri:4k-line",
  title: "4k"
}, {
  icon: "ri:refresh-line",
  title: "Refresh"
}, {
  icon: "ri:add-line",
  title: "Add"
}, {
  icon: "ri:alarm-line",
  title: "Alarm"
}, {
  icon: "ri:apple-line",
  title: "Apple"
}, {
  icon: "ri:archive-line",
  title: "Archive"
}, {
  icon: "ri:arrow-down-line",
  title: "Arrow Down"
}, {
  icon: "ri:arrow-up-line",
  title: "Arrow Up"
}, {
  icon: "ri:play-line",
  title: "Play"
}, {
  icon: "ri:bank-line",
  title: "Bank"
}, {
  icon: "ri:battery-line",
  title: "Battery"
}, {
  icon: "ri:bell-line",
  title: "Bell"
}, {
  icon: "ri:book-line",
  title: "Book"
}, {
  icon: "ri:camera-line",
  title: "Camera"
}, {
  icon: "ri:cloud-line",
  title: "Cloud"
}, {
  icon: "ri:code-line",
  title: "Code"
}, {
  icon: "ri:computer-line",
  title: "Computer"
}, {
  icon: "ri:compass-line",
  title: "Compass"
}, {
  icon: "ri:contacts-line",
  title: "Contacts"
}, {
  icon: "ri:delete-bin-line",
  title: "Delete"
}, {
  icon: "ri:download-line",
  title: "Download"
}, {
  icon: "ri:edit-line",
  title: "Edit"
}, {
  icon: "ri:search-line",
  title: "Search"
}, {
  icon: "ri:file-line",
  title: "File"
}, {
  icon: "ri:filter-line",
  title: "Filter"
}, {
  icon: "ri:flag-line",
  title: "Flag"
}, {
  icon: "ri:folder-line",
  title: "Folder"
}, {
  icon: "ri:gift-line",
  title: "Gift"
}, {
  icon: "ri:home-line",
  title: "Home"
}, {
  icon: "ri:image-line",
  title: "Image"
}, {
  icon: "ri:input-method-line",
  title: "Input"
}, {
  icon: "ri:instagram-line",
  title: "Instagram"
}, {
  icon: "ri:settings-line",
  title: "Settings"
}, {
  icon: "ri:keyboard-line",
  title: "Keyboard"
}, {
  icon: "ri:lightbulb-line",
  title: "Lightbulb"
}, {
  icon: "ri:lock-line",
  title: "Lock"
}, {
  icon: "ri:logout-box-line",
  title: "Logout"
}, {
  icon: "ri:mail-line",
  title: "Mail"
}, {
  icon: "ri:map-pin-line",
  title: "Map"
}, {
  icon: "ri:message-line",
  title: "Message"
}, {
  icon: "ri:more-line",
  title: "More"
}, {
  icon: "ri:notification-line",
  title: "Notification"
}, {
  icon: "ri:shopping-cart-line",
  title: "Shopping Cart"
}, {
  icon: "ri:phone-line",
  title: "Phone"
}];